name: Build Device Tree
description: Build device tree using special image

inputs:
  image-path:
    description: Path of your images
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.image-path }}

