name: Build Recovery Image
description: Build recovery image from device tree

inputs:
  device-name:
    description: ''
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.device-name }}
